### ISSUE TITLE
External Script Module in Release Mode

### ISSUE THREAD

**Issue by ChrisMH** [andrewdavey/cassette#41]
When deployed in release mode and accessing a web site that uses Cassette, Cassette is not finding my external script module.

I have this reference in my CassetteConfiguration:

new ExternalScriptModule("GoogleMapsApi", "https://maps-api-ssl.google.com/maps/api/js?sensor=false")

And I reference it in other .js files like:

<reference path="/GoogleMapsApi"/>

All is well in a debug deployment, however when I deploy in release I get errors like:

Reference error in "googlemap.Map.js", line 1. Cannot find "~\GoogleMapsApi"

I'm using 0.6 from NuGet.

**Comment by andrewdavey** [comment]
It's caused by a bug in the module manifest caching for external modules. Working on a fix now...

**Comment by andrewdavey** [comment]
The latest in master should fix this bug. Can you pull and give it go please?
Thanks.

**Comment by ChrisMH** [comment]
Just pulled from master, the bug is still there.  Unless there's some cache that I need to clear (you mentioned caching above).

**Comment by andrewdavey** [comment]
Did you fix it or close by mistake?

**Comment by ChrisMH** [comment]
Oops.

**Comment by andrewdavey** [comment]
OK, I will do some more testing later today and make sure it's fixed this time :)

Also, can you try changing your reference to use a forward slash instead e.g. `"~/GoogleMapsApi"`? That may work around the problem for now...

**Comment by ChrisMH** [comment]
I am using the forward slash.  I have tried with and without the tilde (~) with the same result.

**Comment by andrewdavey** [comment]
I can't seem to reproduce the bug. Make sure your web application is incrementing the assembly version on build to avoid loading a stale cache e.g. 

```
[assembly: AssemblyVersion("1.0.*")]
```

Are you able to reproduce the bug in a project and send it to me? andrew@equin.co.uk thanks.

**Comment by ChrisMH** [comment]
Looks like it was a caching issue.

Working fine now, thanks.

**Comment by andrewdavey** [comment]
OK I'm glad that's working now. Let me know if you run into any other caching bugs. Since there is code there that is meant to discard the stale cache, and I'll need to fix it if it's broken :)

**Comment by andrewdavey** [comment]
Force a re-build of your web application, assuming your assembly version increments on build `[assembly: AssemblyVersion("1.0.*")]` Cassette uses this to version the cache. On start up it should detect the version change and rebuild the cache.

The other option is to spelunk down into isolated storage... not fun!
